# 1) Code for Printing mysql DataBase Schema

In [2]:
import mysql.connector

Schema = ""
col = []

database='nepa'

# Establish a connection to the database
connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='',
    database='nepa'
)


cursor = connection.cursor()

# Fetch the list of tables in the database
dtables = []
cursor.execute("SHOW TABLES")
tables = cursor.fetchall()

print(f"In Our DataBase {database} we have Following Tables:")
for i in tables:
    print("Table:", i[0])
    dtables.append(i[0])

# Initialize the actual_cols to store the list of column names for each table
actual_cols = []
tabdata = []

for table_name in dtables:
    cursor.execute(f"DESCRIBE {table_name}")
    des = cursor.fetchall()

    # Collect column names for the current table
    cols = [column[0] for column in des]
    actual_cols.append(cols)
    
    cursor.execute(f"SELECT * FROM {table_name} LIMIT 5;")
    rows = cursor.fetchall()
    tabdata.append(rows)

# Loop through each table and describe its schema
for table_name in dtables:
    Schema += f"\nSchema of table `{table_name}`:\n"
    cursor.execute(f"DESCRIBE {table_name}")
    columns = cursor.fetchall()
    
    # Print the header for the schema
    Schema += f'Description of Table {table_name}["Field","Type","Null","Key","Default","Extra"] are given below ==> \n\n'
    
    # Print each column's schema
    for column in columns:
        Schema += str(column) + "\n"

# Output the Schema and col
print(Schema)

print("\n")

print("OUR TABLE CONTAINS DATA LIKE THIS BELOW:")
print('-' * 80)
# Print data for each dataset
for headers, data in zip(actual_cols, tabdata):
    # Print headers
    print(', '.join(headers))
    
    # Print data rows
    
    for row in data:
        print(', '.join(map(str, row)))
    
    # Print a separator
    print('-' * 80)

In Our DataBase nepa we have Following Tables:
Table: pos

Schema of table `pos`:
Description of Table pos["Field","Type","Null","Key","Default","Extra"] are given below ==>

('Unnamed: 0', 'bigint(20)', 'YES', '', None, '')
('Date', 'datetime', 'YES', '', None, '')
('Customer', 'text', 'YES', '', None, '')
('CustomerID', 'bigint(20)', 'YES', '', None, '')
('OdooID', 'text', 'YES', '', None, '')
('OrderReference', 'text', 'YES', '', None, '')
('ProductName', 'text', 'YES', '', None, '')
('UnitPrice', 'double', 'YES', '', None, '')
('OrderQuantity', 'bigint(20)', 'YES', '', None, '')
('Subtotal', 'double', 'YES', '', None, '')
('Company', 'text', 'YES', '', None, '')
('ReceiptNumber', 'text', 'YES', '', None, '')
('Total', 'double', 'YES', '', None, '')



OUR TABLE CONTAINS DATA LIKE THIS BELOW:
--------------------------------------------------------------------------------
Unnamed: 0, Date, Customer, CustomerID, OdooID, OrderReference, ProductName, UnitPrice, OrderQuantity, Subtotal, Company, ReceiptNumber, Total
0, 2024-01-26 20:20:00, green olive market inc, 22384, __export__.res_partner_22384_8924a229, NEPA 2/0001, cutter spray insect repellent 6oz (sport), 4.25, 2, 8.5, nepa 2 wholesale llc, Order 00079-007-0001, 180.21
1, 2024-01-26 20:20:00, green olive market inc, 22384, __export__.res_partner_22384_8924a229, NEPA 2/0001, marlboro blend no. 27 box, 80.75, 1, 80.75, nepa 2 wholesale llc, Order 00079-007-0001, None
2, 2024-01-26 20:20:00, green olive market inc, 22384, __export__.res_partner_22384_8924a229, NEPA 2/0001, duracell aaa 2pk 18 ct copper top, 31.99, 1, 31.99, nepa 2 wholesale llc, Order 00079-007-0001, None
3, 2024-01-26 20:20:00, green olive market inc, 22384, __export__.res_partner_22384_8924a229, NEPA 2/0001, duracell aa 2pk 14 ct copper top, 24.99, 1, 24.99, nepa 2 wholesale llc, Order 00079-007-0001, None
4, 2024-01-26 20:20:00, green olive market inc, 22384, __export__.res_partner_22384_8924a229, NEPA 2/0001, mentos 15-1.32oz rolls (green apple), 12.99, 1, 12.99, nepa 2 wholesale llc, Order 00079-007-0001, None
--------------------------------------------------------------------------------

# 2) Code for Generating DataBase Schema in .txt File

In [3]:
import mysql.connector

Schema = ""
col = []

database = 'nepa'
output_file = 'database_info.txt'

# Establish a connection to the database
connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='',
    database='nepa'
)

cursor = connection.cursor()

# Fetch the list of tables in the database
dtables = []
cursor.execute("SHOW TABLES")
tables = cursor.fetchall()

output_content = [f"In Our DataBase {database} we have Following Tables:\n"]
for i in tables:
    output_content.append(f"Table: {i[0]}\n")
    dtables.append(i[0])

# Initialize the actual_cols to store the list of column names for each table
actual_cols = []
tabdata = []

for table_name in dtables:
    cursor.execute(f"DESCRIBE {table_name}")
    des = cursor.fetchall()

    # Collect column names for the current table
    cols = [column[0] for column in des]
    actual_cols.append(cols)
    
    cursor.execute(f"SELECT * FROM {table_name} LIMIT 5;")
    rows = cursor.fetchall()
    tabdata.append(rows)

# Loop through each table and describe its schema
for table_name in dtables:
    Schema += f"\nSchema of table `{table_name}`:\n"
    cursor.execute(f"DESCRIBE {table_name}")
    columns = cursor.fetchall()
    
    # Print the header for the schema
    Schema += f'Description of Table {table_name}["Field","Type","Null","Key","Default","Extra"] are given below ==> \n\n'
    
    # Print each column's schema
    for column in columns:
        Schema += str(column) + "\n"

output_content.append(Schema + "\n")
output_content.append("Our table contains data like the following. The data below is not complete but serves as a sample to show what type of data our table stores:\n")
output_content.append('-' * 80 + "\n")
# Print data for each dataset
for headers, data in zip(actual_cols, tabdata):
    # Print headers
    output_content.append(', '.join(headers) + "\n")
    
    # Print data rows
    for row in data:
        output_content.append(', '.join(map(str, row)) + "\n")
    
    # Print a separator
    output_content.append('-' * 80 + "\n")

# Write output to file
with open(output_file, 'w') as file:
    file.writelines(output_content)

print("Database information has been written to", output_file)

Database information has been written to database_info.txt

# 3) SQL Query Code

In [7]:
from langchain_ollama import ChatOllama
from langchain.prompts import ChatPromptTemplate
from langchain.chains import LLMChain, SequentialChain
import re
import mysql.connector
import traceback
from langchain_groq import ChatGroq
from tabulate import tabulate


def llm_model(key, model, temp=0, typee=None):
    if typee == "groq":
        llm = ChatGroq(model=model, temperature=temp, groq_api_key=key)
    elif typee == "ollama":
        llm = ChatOllama(model=model, temperature=temp, ollama_api_key=key)
    else:
        raise ValueError("Unsupported model type specified.")
    return llm


def make_connection(host, user, password, db):
    # Establish a connection to the database
    connection = mysql.connector.connect(
        host=host,
        user=user,
        password=password,
        database=db
    )
    return connection


def generator_prompt(llm):
    # Define prompt chains
    first_prompt = ChatPromptTemplate.from_template(
        template="""
            You are a helpful assistant specialized in generating SQL queries. Your first task is to understand the user's intent based on their question.
            
            User Question: "{user_question}" 
            
            Task: Summarize the user's intent in one sentence."""
    )

    chain_one = LLMChain(llm=llm, prompt=first_prompt, output_key="user_intent")

    second_prompt = ChatPromptTemplate.from_template(
        "Given the following database schema: {schema}, generate an SQL query that fulfills the user intent described below:\n\n"
        "User Intent: {user_intent}\n\n"
        "Ensure the query is optimized and accurately reflects the intent."
    )

    chain_two = LLMChain(llm=llm, prompt=second_prompt, output_key="prequery")

    third_prompt = ChatPromptTemplate.from_template(
        "From this text, I want only the SQL part text. Remove other unnecessary things: \n\n{prequery}"
    )

    chain_three = LLMChain(llm=llm, prompt=third_prompt, output_key="finalsql")

    fourth_prompt = ChatPromptTemplate.from_template(
        "Verify whether the query '{finalsql}' corresponds to the user's question: '{user_question}' based on the given schema: '{schema}'. Provide only the final SQL code."
    )

    chain_four = LLMChain(llm=llm, prompt=fourth_prompt, output_key="ffinalsql")

    # Combine the chains
    overall_chain = SequentialChain(
        chains=[chain_one, chain_two, chain_three, chain_four],
        input_variables=["user_question", "schema"],
        output_variables=["user_intent", "prequery", "finalsql", "ffinalsql"],
        verbose=True
    )

    return overall_chain


def generate_sql(user_question, schema_path, llm):
    # Load the schema from the given path
    with open(schema_path, 'r') as file:
        schema = file.read()

    # Initialize the prompt generator with the schema
    generate_prompt = generator_prompt(llm)

    # Run the SequentialChain with the inputs
    result = generate_prompt.invoke({
        "user_question": user_question,
        "schema": schema
    })

    # Display results for debugging
    print("User Intent:", result.get("user_intent", "Not available"))
    print("-" * 100)
    print("Pre-query:", result.get("prequery", "Not available"))
    print("-" * 100)
    print("Final SQL:", result.get("finalsql", "Not available"))
    print("-" * 100)
    print("Super Final SQL:", result.get("ffinalsql", "Not available"))
    print("-" * 100)

    def extract_clean_sql(text):
        """Helper function to extract and clean SQL query from the provided text."""
        match = re.search(r"SELECT.*?;", text, re.DOTALL)
        if match:
            sql_query = match.group()
            if "\n" in sql_query:
                return ' '.join(sql_query.replace('\n', ' ').split())
            else:
                return sql_query
        return None

    # Try to extract from 'ffinalsql' first
    text = str(result.get("ffinalsql", ""))
    cleaned_query = extract_clean_sql(text)

    if cleaned_query:
        return cleaned_query, schema

    # Fallback to 'finalsql' if not found in 'ffinalsql'
    text = str(result.get("finalsql", ""))
    cleaned_query = extract_clean_sql(text)

    if cleaned_query:
        return cleaned_query, schema

    # If no SQL found in either, print and return None
    print("No SQL query found in the text from both 'ffinalsql' and 'finalsql'.")
    return None, None


def run_sqlgenie(connection, sql_query, schema, llms):
    """
    Attempts to run a SQL query and correct it using a list of LLMs if an error occurs.

    Parameters:
    - connection: The MySQL database connection object.
    - sql_query: The initial SQL query to be executed.
    - schema: The database schema to reference for corrections.
    - llms: A list of LLM instances to use for corrections in sequence.

    Returns:
    - The results of the SQL query if successful, otherwise None.
    """
    try:
        cursor = connection.cursor()
        cursor.execute(sql_query)
        result = cursor.fetchall()
        print("SQL Query Results:", result)
        return result
    except Exception as e:
        # Capture the error traceback in a variable
        print("An error occurred while executing the SQL query.")
        error = traceback.format_exc()

        print("\n")
        
        # Iterate through each LLM in the list
        for i, llm in enumerate(llms):
            print(f"Trying corrections with LLM {i + 1}...")

            # Attempt to correct the SQL query up to 3 times with the current LLM
            for attempt in range(3):
                corrected_sql = correct_sql(sql_query, error, schema, llm)
                if corrected_sql:
                    try:
                        cursor.execute(corrected_sql)
                        result = cursor.fetchall()
                        print(f"Corrected SQL Query Results with LLM {i + 1} (Attempt {attempt + 1}):", result)
                        return result
                    except Exception as e:
                        print(f"Corrected query failed on attempt {attempt + 1} with LLM {i + 1}:")

        # If all attempts with all LLMs fail, return None
        print("Failed to correct SQL query after multiple attempts with all LLMs.")
      
        return None

def correct_sql(incorrect_sql, error, schema, llm):
    # Prompt template for correcting SQL
    first_prompt_correct = ChatPromptTemplate.from_template(
        template="""
            You are a SQL queries validator. Your task is to correct incorrect queries. You will always receive an incorrect query as input.

            The incorrect query is: {incorrect_sql}.

            The error is: {err}. 

            The database schema is: {sch}.

            Task: Your job is to fix the incorrect query based on the provided error and refer to the database schema for corrections.
        """
    )

    chain_one_corr = LLMChain(llm=llm, prompt=first_prompt_correct, output_key="cor1")

    second_prompt_correct = ChatPromptTemplate.from_template(
        template="""
            Extract and provide only the SQL code from the following corrected text: {cor1}.
            
            Task: Focus solely on filtering out/ and returning the SQL code, ignoring any other text or information in the paragraphs.
        """
    )

    chain_two_corr = LLMChain(llm=llm, prompt=second_prompt_correct, output_key="ffquery")

    overall_chain_cor = SequentialChain(
        chains=[chain_one_corr, chain_two_corr],
        input_variables=["incorrect_sql", "err", "sch"],
        output_variables=["cor1", "ffquery"],
        verbose=True
    )

    result_cor = overall_chain_cor.invoke({
        "incorrect_sql": incorrect_sql,
        "err": error,
        "sch": schema,
    })

    corrected_text = str(result_cor["ffquery"])

    # Extract corrected SQL query using regex
    match = re.search(r"SELECT.*?;", corrected_text, re.DOTALL)

    if match:
        corrected_sql_query = match.group()
        print("Corrected SQL Query:", corrected_sql_query)
        return corrected_sql_query
    else:
        print("No corrected SQL query found in the text.")
        return None

In [97]:
key="put_your_key"

In [16]:

# Define your LLM instances
llm1 = llm_model(key, model="mixtral-8x7b-32768", typee='groq')  # First LLM instance
llm2 = llm_model(key, model="gemma2-9b-it", typee='groq')   # Second LLM instance
llm3 = llm_model(key, model="llama3-8b-8192", typee='groq')  # Third LLM instance

# List of LLMs to use
llms = [llm1, llm2, llm3]

# Connect to your database
conn = make_connection(host='localhost', user="root", password='', db='nepa')


prompt1=generator_prompt(llm1)

In [22]:
def harmful_query():
    synonyms = [
        # Insert
        "Add", "Include", "Enter", "Inject", "Append", "Embed", "Introduce", "Place", "Put in", "Infix",
        "Incorporate", "Implant", "Enclose", "Attach", "Set in", "Imbed", "Insert into", "Fit in", "Integrate",
        "Lodge", "Interpose", "Position", "Intercalate", "Introduce into", "Slip in", "Embed into", "Stick in",
        "Insinuate", "Interject", "Tuck in", "Nest", "Slide in", "Slip into", "Enfold", "Accommodate",
        "Interpolate", "Fill in", "Slot in", "Interlace", "Squeeze in", "Put into place", "Arrange", "Accompany",
        "Reinsert", "Fix", "Plant", "Install", "Implant into", "Embed with", "Enjoin", "Insert",
        
        # Drop
        "Remove", "Omit", "Exclude", "Discard", "Eliminate", "Abandon", "Withdraw", "Cancel", "Dismiss",
        "Detach", "Cut out", "Erase", "Forget", "Leave out", "Set aside", "Forsake", "Depose", "Disregard",
        "Eject", "Cast aside", "Discharge", "Discard", "Jettison", "Shed", "Unload", "Relinquish", "Curtail",
        "Revoke", "Suppress", "Terminate", "Unlink", "Take away", "Detach", "Cut off", "Cut down", "Cull",
        "Wean off", "Decouple", "Deselect", "Excise", "Pare down", "Truncate", "Sift out", "Sever", "Deprecate",
        "Reduce", "Rescind", "Surrender", "Slough off", "Waive", "Drop",
        
        # Delete
        "Remove", "Erase", "Expunge", "Clear", "Wipe out", "Obliterate", "Cancel", "Purge", "Exterminate",
        "Cut", "Annihilate", "Eliminate", "Excise", "Strike out", "Remove", "Obliterate", "Edit out",
        "Exclude", "Drop", "Dismiss", "Liquidate", "Nullify", "Abolish", "Invalidate", "Deprecate",
        "Cancel out", "Expurgate", "Obliterate", "Edit away", "Wipe off", "Extinguish", "Cross out",
        "Suppress", "Deactivate", "Deprecate", "Omit", "Dissolve", "Void", "Close", "Extirpate", "Null",
        "Retire", "Snuff out", "Banish", "Eradicate", "Remove traces", "Obliterate signs", "Zap", "Delete",
        "Cut out", "Trim",
        
        # Create
        "Generate", "Produce", "Construct", "Build", "Develop", "Form", "Establish", "Initiate", "Originate",
        "Design", "Invent", "Craft", "Fabricate", "Compose", "Manufacture", "Formulate", "Engender", "Assemble",
        "Shape", "Model", "Make", "Construct", "Compile", "Concoct", "Devise", "Forge", "Conceive", "Plan",
        "Spawn", "Compose", "Sculpt", "Render", "Erect", "Contribute", "Synthesize", "Bring into being",
        "Formulate", "Engineer", "Innovate", "Launch", "Pioneer", "Institute", "Brew", "Architect", "Invent",
        "Produce", "Draw up", "Hatch", "Realize", "Author", "Create"
    ]

    # Convert synonyms to lowercase for case-insensitive comparison
    lower_synonyms = set(word.lower() for word in synonyms)

    def contains_synonym(question):
        # Convert question to lowercase and split into words
        words = set(question.lower().split())
        # Check if any word in the question is in the synonyms list
        return any(word in lower_synonyms for word in words)

    while True:
        question = input("Please enter your question: ")
        
        if contains_synonym(question):
            print("Your question contains restricted words. Please rephrase it.")
        else:
            print("Your question has been accepted.")
            return question

# Call the function
user_question = harmful_query()

 # user_question = give me the name of the customer who buys most products

print("Stored input:", user_question)

Your question has been accepted.
Stored input: give me the name of the customer who buys most products

In [23]:
sql, schema=generate_sql(user_question,"database_info.txt",llm1)

> Entering new SequentialChain chain...

> Finished chain.
User Intent: The user wants to retrieve the name of the customer who has made the highest number of purchases.
----------------------------------------------------------------------------------------------------
Pre-query: To fulfill the user intent, we need to find the customer with the highest number of orders. We can achieve this by grouping the data by the CustomerID and then counting the number of rows for each customer. We will then select the customer with the maximum count.

Here's the SQL query to achieve this:

```sql
SELECT Customer
FROM pos
GROUP BY CustomerID
ORDER BY COUNT(*) DESC
LIMIT 1;
```

Explanation:

1. `SELECT Customer`: We select the Customer field to display the name of the customer.
2. `FROM pos`: We select data from the `pos` table.
3. `GROUP BY CustomerID`: We group the data by the CustomerID to count the number of orders for each customer.
4. `ORDER BY COUNT(*) DESC`: We order the results by the count of rows in descending order, so the customer with the highest number of orders appears first.
5. `LIMIT 1`: We limit the results to only one row, which will be the customer with the highest number of orders.
----------------------------------------------------------------------------------------------------
Final SQL: Here's the SQL query to achieve this:

```sql
SELECT Customer
FROM pos
GROUP BY CustomerID
ORDER BY COUNT(*) DESC
LIMIT 1;
```

Explanation:

1. `SELECT Customer`
2. `FROM pos`
3. `GROUP BY CustomerID`
4. `ORDER BY COUNT(*) DESC`
5. `LIMIT 1`
----------------------------------------------------------------------------------------------------
Super Final SQL: The SQL query corresponds to the user's question 'give me the name of the customer who buys most products' based on the given schema.

Here's the final SQL code:
```sql
SELECT `Customer`
FROM `pos`
GROUP BY `CustomerID`
ORDER BY COUNT(*) DESC
LIMIT 1;
```
Note: I enclosed the table and column names with backticks (`) to avoid any issues with reserved keywords or special characters.
----------------------------------------------------------------------------------------------------

In [24]:
print(sql)

SELECT `Customer` FROM `pos` GROUP BY `CustomerID` ORDER BY COUNT(*) DESC LIMIT 1;

In [25]:
# Run the SQL genie function
results = run_sqlgenie(connection=conn, sql_query=sql, schema=schema, llms=llms)

SQL Query Results: [('finex intl inc',)]

In [26]:
results

[('finex intl inc',)]

In [27]:

print(tabulate(results))

--------------
finex intl inc
--------------